##############################################################################
#########################     Travis CI Settings     #########################
##############################################################################

language: python
group: stable
os: linux
dist: trusty      # options: [precise|trusty]

notifications:
  email:
    on_success: never   # options: [always|never|change]
    on_failure: change  # options: [always|never|change]

cache:
  pip: false
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake

branches:
  only:
    - master
    - develop

python:
  - 2.7
  - 3.4

env:
  - BUILD_TYPE=Debug FC=gfortran-7 USE_OPENMP=ON OMP_NUM_THREADS=4
  - BUILD_TYPE=Debug FC=gfortran-7 USE_OPENMP=ON OMP_NUM_THREADS=4
  - BUILD_TYPE=Release FC=gfortran-6 USE_OPENMP=ON OMP_NUM_THREADS=4
  - BUILD_TYPE=Release FC=gfortran-6 USE_OPENMP=ON OMP_NUM_THREADS=4

addons: &gfortran7
  apt:
    packages:
      - gfortran-7
      - gfortran-6
      - libblas-dev
      - liblapack-dev
      - gmsh
    sources: &sources
      - ubuntu-toolchain-r-test

jobs:
  include:
    - stage: deploy
      if: branch = master
      python: 3.4
      #env:
      #- BUILD_TYPE=Release
      #- FC=gfortran-7
      #- USE_OPENMP=ON
      #- OMP_NUM_THREADS=4
      addons:
        apt:
          packages:
            - graphviz  # For FORD docs
          sources: &sources
            - ubuntu-toolchain-r-test
      install:
      - pip install -r requirements.txt
      script:
      - make docs
      - cd $TRAVIS_BUILD_DIR
      - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
      - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
      - bash ./deploy.sh

########################################################################
#########################   Begin Build Steps   ########################
########################################################################

before_install:
  - openssl aes-256-cbc -K $encrypted_614a5b0d391b_key -iv $encrypted_614a5b0d391b_iv -in .deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key

install:
  - pip install -r requirements.txt
  #- mkdir -p $TRAVIS_BUILD_DIR/bin
  #- which "gfortran-$GCC_VERSION"
  #- ln -sf "$(which gfortran-$GCC_VERSION)" $TRAVIS_BUILD_DIR/bin/gfortran
  #- export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  #- which gfortran
  #- export FC=gfortran
  - echo 'Fortran compiler version:'
  - $FC -v
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.0-Linux-x86_64.tar.gz"
      mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    fi
    export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
  - cmake --version
  - echo "Wow we installed everything!"

before_script:
  - cd $TRAVIS_BUILD_DIR

script:
  - make cleantest
