notifications:
  email: change

language: python

python:
  - 3.5

env:
  global:
    - gfortran=gfortran-6

cache:
  apt: false
  pip: false

branches:
  only:
    - master

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - git
      - gfortran-6
      - python-pip
      - graphviz
      - libblas-dev
      - liblapack-dev
      - gmsh

before_install:
  - openssl aes-256-cbc -K $encrypted_614a5b0d391b_key -iv $encrypted_614a5b0d391b_iv -in .deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key

install:
  - pip install --upgrade graphviz
  - pip install --upgrade meshio
  - (pip install --upgrade ford && ford --version)

script:
  - make clean
  - make build
  - make run
  - DEBUG=no make clean run
  - make docs

after_success:
  - cd $TRAVIS_BUILD_DIR
  - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
  - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
  - bash ./deploy.sh
