##############################
##### Travis CI Settings #####
##############################

language: python
group: stable
os: linux
dist: trusty      # options: [precise|trusty]

notifications:
  email:
    on_success: never   # options: [always|never|change]
    on_failure: change  # options: [always|never|change]

cache:
  apt: true
  pip: true
    - $HOME/.cache/pip
    - $HOME/.local
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake

python:
  - 3.4
env:
  - DEBUG=0
  - DEBUG=1

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
      - gfortran-6
      - valgrind
      - graphviz
      - libblas-dev
      - liblapack-dev
      - gmsh
      # - cmake
    sources: &sources
      - ubuntu-toolchain-r-test
      # - kalakris-cmake

#############################
##### Begin Build Steps #####
#############################

before_install:
  - openssl aes-256-cbc -K $encrypted_614a5b0d391b_key -iv $encrypted_614a5b0d391b_iv -in .deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key

install:
  - pip install --upgrade graphviz
  - pip install --upgrade meshio
  - (pip install --upgrade ford && ford --version)
  - mkdir -p $TRAVIS_BUILD_DIR/bin
  - ln -sf "$(which gfortran-6)" $TRAVIS_BUILD_DIR/bin/gfortran
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
  - |
    CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.0-Linux-x86_64.tar.gz"
    mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
    export PATH="${DEPS_DIR}/cmake/bin:${PATH}"

before_script:
  - gfortran -v
  - cmake --version
  - echo "Wow we installed everything!"

script:
  - make clean
  - make build
  - make cmake
  - make run
  - make docs

################################
##### Deploy if Successful #####
################################

after_success:
  - cd $TRAVIS_BUILD_DIR
  - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
  - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
  - bash ./deploy.sh
