language: python
group: stable
os: linux
dist: precise

notifications:
  email: change  # options: [always|never|change]

python:
  - 3.4

cache:
  apt: false
  pip: false
    # - $HOME/.cache/pip
    # - $HOME/.local

branches:
  only:
    - master
    - develop

addons:
  sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
  apt:
    packages:
      - graphviz
      - libblas-dev
      - liblapack-dev
      - gmsh
      - gfortran-6

before_install:
  - openssl aes-256-cbc -K $encrypted_614a5b0d391b_key -iv $encrypted_614a5b0d391b_iv -in .deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key

install:
  - pip install --upgrade graphviz
  - pip install --upgrade meshio
  - (pip install --upgrade ford && ford --version)

before_script:
  - ln -fs "$(which gfortran-6)" "$HOME/bin/gfortran" && gfortran --version
  - echo "Wow we installed everything!"

script:
  - make clean
  - make build
  - make run
  - DEBUG=no make clean run
  - make docs

after_success:
  - cd $TRAVIS_BUILD_DIR
  - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn' $TRAVIS_COMMIT)"
  - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
  - bash ./deploy.sh
