language: python
group: stable
os: linux
dist: trusty
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  pip: false
  directories:
  - "${TRAVIS_BUILD_DIR}/deps/cmake"
branches:
  only:
  - master
  - develop
python:
- 3.6
env:
- BUILD_TYPE=Debug FC=gfortran-6 USE_OPENMP=ON OMP_NUM_THREADS=4
- BUILD_TYPE=Release FC=gfortran-6 USE_OPENMP=ON OMP_NUM_THREADS=4
addons:
  apt:
    packages:
    - gfortran-6
    - libblas-dev
    - liblapack-dev
    - gmsh
    sources:
    - ubuntu-toolchain-r-test
jobs:
  include:
  - stage: deploy
    if: branch = master
    python: 3.6
    addons:
      apt:
        packages:
        - graphviz
        sources:
        - ubuntu-toolchain-r-test
    install:
    - pip install pipenv
    - pipenv sync
    script:
    - make docs
    - cd $TRAVIS_BUILD_DIR
    - git config --global user.name "TRAVIS-CI-for-$(git --no-pager show -s --format='%cn'
      $TRAVIS_COMMIT)"
    - git config --global user.email "$(git --no-pager show -s --format='%ce' $TRAVIS_COMMIT)"
    - bash ./deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_614a5b0d391b_key -iv $encrypted_614a5b0d391b_iv
  -in .deploy_key.enc -out .deploy_key -d
- chmod 600 .deploy_key
install:
- pip install pipenv
- pipenv sync --dev
- echo 'Fortran compiler version:'
- "$FC -v"
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
- |
  if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
    CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.0-Linux-x86_64.tar.gz"
    mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
  fi
  export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
- cmake --version
- echo "Wow we installed everything!"
before_script:
- cd $TRAVIS_BUILD_DIR
script:
- make cleanslowtest
