integrate_basis_1d – learn_dg
integrate_basis_1d Function
28 statements
Source File
private function integrate_basis_1d(order, basis_num, dx) result(integral)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: order
integer, intent(in) :: basis_num
integer, intent(in) :: dx
Return Value real(kind=wp)
Calls
Source Code
integrate_basis_1d
Source Code
  function integrate_basis_1d(order, basis_num, dx) result(integral)
    integer, intent(in) :: order, basis_num, dx
    real(wp)            :: integral
    real(wp), dimension(:, :), allocatable:: Vinv
    allocate(Vinv(order+1, order+1))
    call vandermonde(order+1, Vinv)
    ! call r8mat_print(order+1, order+1, Vinv, 'Inverse Vandermonde')
    ! Check to make sure requested basis number is within available basis
    if ( basis_num > order+1 ) then
      write(*,*) 'The basis_num input is larger than number of available basis nodes (order+1)'
      write(*,*) 'Make sure order and basis_num are correctly set before calling'
      stop
    endif
    ! Check to make sure differentiation is either 0 or 1
    if ( dx < 0 .or. dx > 1 ) then
      write(*,*) 'Derivatives of order lower than 0 or higher than 1 are not allowed'
      write(*,*) 'integrate_basis_1d was called with dx = ', dx
      write(*,*) 'Check to make sure that the function was called correctly'
      stop
    endif
    call integrate(local_basis_1D, -1.0_wp, 1.0_wp, integral)
    deallocate(Vinv)
    return
  contains
    subroutine local_basis_1D(x, y)
      real(wp), intent(in), dimension(:) :: x
      real(wp), intent(out), dimension(:) :: y
      y = basis_1D(x, Vinv(:, basis_num), dx)
      return
    end subroutine local_basis_1D
  end function integrate_basis_1d
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_wrapper get_command_argument_wrapper getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs vandermonde write_out_solution
Call graph
integrate_basis_1d calls integrate, vandermonde
integrate calls gaussquad
vandermonde calls linspace, linsolve_quick
linsolve_quick calls linsolve
linsolve calls dgetrs, dgetrf