integrate_basis_1d_Ie – learn_dg
integrate_basis_1d_Ie Function
43 statements
Source File
private function integrate_basis_1d_Ie(N, ii, jj, dx1, dx2, xcoords) result(integral)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
integer, intent(in) :: ii
integer, intent(in) :: jj
integer, intent(in) :: dx1
integer, intent(in) :: dx2
real(kind=wp), intent(in), dimension(:) :: xcoords
Return Value real(kind=wp)
Calls
Called By
Source Code
integrate_basis_1d_Ie
Source Code
  function integrate_basis_1d_Ie(N, ii, jj, dx1, dx2, xcoords) result(integral)
    integer, intent(in)                     :: N, ii, jj, dx1, dx2
    real(wp), intent(in), dimension(:)      :: xcoords
    real(wp)                                :: integral
    integer                                 :: order, basis_num1, basis_num2
    real(wp), dimension(:, :), allocatable  :: Vinv
    order = N
    basis_num1 = ii
    basis_num2 = jj
    allocate(Vinv(order+1, order+1))
    call vandermonde(order+1, Vinv)
    ! Check to make sure xcoords is an array of size (N+1)
    if ( size(xcoords) /=  order+1 ) then
      write(*,*) 'The shape of `xcoords` is outside the acceptable range for a'
      write(*,*) '1D basis function.'
      write(*,*) 'Shape(xcoords) should be [', 2, order+1, '], not ', shape(xcoords)
    endif
    call integrate(local_wrapper, -1.0_wp, 1.0_wp, integral)
    return
  contains
    subroutine XorJ(s, dx, out)
      integer, intent(in)                  :: dx
      real(wp), intent(in),   dimension(:) :: s
      real(wp), intent(out),  dimension(:) :: out
      integer                              :: ii
      out = 0.0_wp
      do ii = 1, size(xcoords)
        out = out + basis_1D(s, Vinv(:, ii), dx) * xcoords(ii)
      enddo
    end subroutine XorJ
    subroutine local_wrapper(s, y)
      real(wp), intent(in),   dimension(:)  :: s
      real(wp), intent(out),  dimension(:)  :: y
      real(wp), dimension(:), allocatable   :: J
      allocate(J(size(s)))
      call XorJ(s, 1, J)
      ! write(*,*) dx1, dx2
      y = 1.0_wp
      ! Here we have to be careful because J is not always needed in the first
      ! two function calls. Instead of using if statements, we can use an exponent so that when dx_ == 0, J is 1
      y = y * basis_1D(s, Vinv(:, basis_num1), dx1) / (J**real(dx1,wp))
      y = y * basis_1D(s, Vinv(:, basis_num2), dx2) / (J**real(dx2,wp))
      y = y * J
      deallocate(J)
      return
    end subroutine local_wrapper
  end function integrate_basis_1d_Ie
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_wrapper get_command_argument_wrapper getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs vandermonde write_out_solution
Call graph
integrate_basis_1d_ie calls integrate, vandermonde
integrate calls gaussquad
vandermonde calls linspace, linsolve_quick
linsolve_quick calls linsolve
linsolve calls dgetrs, dgetrf
getie calls integrate_basis_1d_ie