vandermonde – learn_dg
vandermonde Subroutine
16 statements
Source File
private subroutine vandermonde(n, Vinv)
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=wp), dimension(n, n) :: Vinv
Calls
Called By
Source Code
vandermonde
Source Code
  subroutine vandermonde(n, Vinv)
    integer:: ii, jj
    integer:: n
    real(wp), dimension(n):: x
    real(wp), dimension((n)**2):: V_flat
    real(wp), dimension(n, n):: V, Vinv, eye
    call linspace(-1._wp, 1._wp, x)
    V_flat = [( [( [x(ii)**real(jj-1, wp)], ii = 1, n)], jj = 1, n)]
    V = reshape([ V_flat ], [ n, n ])
    ! call r8mat_print(n, n, V, 'Original V Matrix: ')
    eye = 0._wp
    do ii = 1, n
      eye(ii,ii) = 1._wp
    enddo
    call linsolve_quick (n, V, n, eye, Vinv)
    return
  end subroutine vandermonde
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_wrapper get_command_argument_wrapper getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs vandermonde write_out_solution
Call graph
vandermonde calls linsolve_quick, linspace
linsolve_quick calls linsolve
linsolve calls dgetrs, dgetrf
integrate_basis_1d calls vandermonde
integrate_basis_1d_ie calls vandermonde
getie calls integrate_basis_1d_ie