assembleElementalMatrix1D – learn_dg
assembleElementalMatrix1D Module Function
14 statements
Source File
function assembleElementalMatrix1D(N, d1, d2, xy) result(Ie)
Routine to calculate the elemental mass/stiffness matrix based on the derivatives of the basis functions.
Currently only zero-th and first order derivatives are supported. Second order derivatives need to be reduced to first order derivatives in the problem formulation using Green's Theorem (i.e. derivation by parts)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
Number of nodes in basis function
integer, intent(in) :: d1
Derivative of the first basis function
integer, intent(in) :: d2
Derivative of the second basis function
real(kind=wp), intent(in), dimension(N) :: xy
Coordinates of the 1D line element
Return Value real(kind=wp), dimension(N,N)
Output elemental matrix
Calls
Called By
Source Code
assembleElementalMatrix1D
Source Code
  module function assembleElementalMatrix1D(N, d1, d2, xy) result(Ie)
    !*  Routine to calculate the elemental mass/stiffness matrix based on the
    !   derivatives of the basis functions.
    !
    !   Currently only zero-th and first order derivatives are supported. Second
    !   order derivatives need to be reduced to first order derivatives in the
    !   problem formulation using Green's Theorem (i.e. derivation by parts)
    integer,  intent(in)                    :: N        !! Number of nodes in basis function
    integer,  intent(in)                    :: d1       !! Derivative of the first basis function
    integer,  intent(in)                    :: d2       !! Derivative of the second basis function
    real(wp), intent(in),   dimension(N)    :: xy       !! Coordinates of the 1D line element
    real(wp),               dimension(N,N)  :: Ie       !! Output elemental matrix
    integer :: ii, jj, order
    Ie = 0._wp
    order = size(xy)-1
    do ii = 1, size(xy)
      Ie(ii, :) = [( integrate_basis_1d_Ie(order, ii, jj, d1, d2, xy), jj = 1, order+1 )]
    enddo
    return
  end function assembleElementalMatrix1D
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt create_simple_array_c det2 eye fun1d_interf fun2d_interf gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getJacobian getXY getXY initialize_global_mats integrate integrate1D integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_2D_row pascal_row pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs write_out_solution
Call graph
assembleelementalmatrix1d calls integrate_basis_1d_ie
integrate_basis_1d_ie calls integrate, getalpha
integrate calls integrate1d, integrate2d
integrate1d calls gaussquad
integrate2d calls gaussquad
gaussquad calls gaussquad, gaussquad_rosetta
assemble1d calls assembleelementalmatrix1d