assembleElementalMatrix – learn_dg
assembleElementalMatrix Function
51 statements
Source File
public function assembleElementalMatrix(N, d1, d2, xy) result(Ie)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
integer, intent(in) :: d1
integer, intent(in) :: d2
real(kind=wp), intent(in), dimension(N,2) :: xy
Return Value real(kind=wp), dimension(N,N)
Calls
Source Code
assembleElementalMatrix
Source Code
  function assembleElementalMatrix(N, d1, d2, xy) result(Ie)
    ! Dummy variables
    integer,                  intent(in)  :: N, d1, d2
    real(wp), dimension(N,2), intent(in)  :: xy
    real(wp), dimension(N,N)              :: Ie
    ! Local variables
    integer                   :: N1, N2
    real(wp), dimension(N,N)  :: alpha
    ! Get the coefficients of the basis functions (alpha). Both bi-linear (N=4)
    ! and bi-quadratic (N=9) quadrilaterals are supported.
    alpha = getAlpha(N)
    Ie = 0._wp
    do N1 = 1, N
      do N2 = 1, N
        ! fun is now implicitly defined using the following: N1, N2, d1, and d2
        Ie(N1,N2) = Ie(N1,N2) + integrate2D(fun)
      enddo
    enddo
  contains
    function fun(xi, eta) result(out)
      ! Dummy variables
      real(wp), dimension(:,:), intent(in)  :: xi, eta
      real(wp), dimension(:,:), allocatable :: out
      ! Local variables
      integer                   :: ii, jj, num_pts
      real(wp), parameter       :: eps = epsilon(0e0)
      real(wp)                  :: fun1, fun2
      real(wp), dimension(2)    :: dfun1, dfun2
      real(wp)                  :: detJ
      real(wp), dimension(2,2)  :: J, invJ
      ! Initialize function output. Actual number of pts is num_pts*num_pts,
      ! because the meshgrid goes in both x and y directions. Only need one.
      num_pts = size(xi,1)
      allocate(out(num_pts,num_pts))
      out = 0._wp
      do ii = 1, num_pts
        do jj = 1, num_pts
          ! Calculate Jacobian, inverse Jacobian, and determinant of finite
          ! element at (xi,eta)
          J     = getJacobian(N, xi(ii,jj), eta(ii,jj), xy, alpha)
          invJ  = inv2(J)
          detJ  = det2(J)
          ! If fun1 is just N_i, use dot_product to determine N_i
          if ( d1 == 0 ) then
            fun1 = dot_product(alpha(:,N1), getArow(N, xi(ii,jj), eta(ii,jj)))
          else
            ! If fun1 contains a derivative, need to calc N_i,xi and N_i,eta
            dfun1(1) = ( &
              dot_product(alpha(:,N1), getArow(N, xi(ii,jj)+eps, eta(ii,jj))) - &
              dot_product(alpha(:,N1), getArow(N, xi(ii,jj)-eps, eta(ii,jj))) &
              ) / ( 2._wp*eps )
            dfun1(2) = ( &
              dot_product(alpha(:,N1), getArow(N, xi(ii,jj), eta(ii,jj)+eps)) - &
              dot_product(alpha(:,N1), getArow(N, xi(ii,jj), eta(ii,jj)-eps)) &
              ) / ( 2._wp*eps )
            ! N_i,x = dxi/dx * N_i,xi + deta/dx * N_i,eta
            fun1 = dot_product(invJ(d1,:), dfun1)
          endif
          ! If fun2 is just N_i, use dot_product to determine N_i
          if ( d2 == 0 ) then
            fun2 = dot_product(alpha(:,N2), getArow(N, xi(ii,jj), eta(ii,jj)))
          else
            ! If fun2 contains a derivative, need to calc N_i,xi and N_i,eta
            dfun2(1) =  ( &
              dot_product(alpha(:,N2), &
                          getArow(N, xi(ii,jj)+eps, eta(ii,jj))) - &
              dot_product(alpha(:,N2), &
                          getArow(N, xi(ii,jj)-eps, eta(ii,jj))) &
                        ) / ( 2._wp*eps )
            dfun2(2) =  ( &
              dot_product(alpha(:,N2), getArow(N, xi(ii,jj), eta(ii,jj)+eps)) - &
              dot_product(alpha(:,N2), getArow(N, xi(ii,jj), eta(ii,jj)-eps)) &
                        ) / ( 2._wp*eps )
            ! N_i,y = dxi/dy * N_i,xi + deta/dy * N_i,eta
            fun2 = dot_product(invJ(d2,:), dfun2)
          endif
          out(ii,jj) = fun1 * fun2 * detJ
        enddo
      enddo
      return
    end function fun
  end function assembleElementalMatrix
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_rosetta getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_2D_row pascal_row r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs sub1d_interf vandermonde write_out_solution
Call graph
assembleelementalmatrix calls getalpha, integrate2d
getalpha calls linsolve_quick, eye
linsolve_quick calls linsolve
linsolve calls dgetrf, dgetrs