assemble1D – learn_dg
assemble1D Subroutine
25 statements
Source File
subroutine assemble1D(points, cells, diff, vel, GlobalA)
Assemble the global stiffness matrix based on element connectivity
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: points
Array of nodal coordinates
integer, intent(in), dimension(:,:) :: cells
Element connectivity
real(kind=wp), intent(in) :: diff
Diffusivity coefficient [m/s^2]
real(kind=wp), intent(in) :: vel
Velocity [m/s]
real(kind=wp), intent(out), dimension(:,:) :: GlobalA
Global Stiffness matrix
Calls
Source Code
assemble1D
Source Code
  subroutine assemble1D(points, cells, diff, vel, GlobalA)
    !* Assemble the global stiffness matrix based on element connectivity
    integer,  intent(in),   dimension(:,:)  :: cells    !! Element connectivity
    real(wp), intent(in)                    :: diff     !! Diffusivity coefficient [m/s^2]
    real(wp), intent(in)                    :: vel      !! Velocity [m/s]
    real(wp), intent(in),   dimension(:)    :: points   !! Array of nodal coordinates
    real(wp), intent(out),  dimension(:,:)  :: GlobalA  !! Global Stiffness matrix
    integer               :: ii, num_cells, num_pts
    real(wp), parameter   :: eps = epsilon(1e0)
    real(wp), allocatable :: xy(:), Ie(:,:)
    GlobalA   = 0._wp
    num_cells = size(cells, 1)
    ! Add elemental stiffness matrices to Global Stiffness Matrix
    !$OMP PARALLEL DEFAULT(SHARED) PRIVATE(ii, xy, Ie) REDUCTION(+:GlobalA)
    !$OMP DO
    do ii = 1, num_cells
      num_pts   = size(cells(ii,:))
      ! Reallocate elemental stiffness matrix
      allocate(xy(num_pts), Ie(num_pts, num_pts))
      xy = points(cells(ii,:))
      Ie = assembleElementalMatrix1D(num_pts, 1, 1, xy)
      ! call r8mat_print(num_pts, num_pts, Ie, 'Elemental Stiffness Matrix:')
      GlobalA(cells(ii,:), cells(ii,:)) = &
          GlobalA(cells(ii,:), cells(ii,:)) - diff*Ie
      if ( abs(vel) .gt. eps ) then
        Ie = assembleElementalMatrix1D(num_pts, 0, 1, xy)
        ! call r8mat_print(num_pts, num_pts, Ie, 'Elemental Stiffness Matrix:')
        GlobalA(cells(ii,:), cells(ii,:)) = &
            GlobalA(cells(ii,:), cells(ii,:)) - vel*Ie
      endif
      ! Deallocate elemental stiffness matrix after every loop
      deallocate(Ie, xy)
      ! stop
    enddo
    !$OMP END DO
    !$OMP END PARALLEL
    ! call r8mat_print(num_nodes, num_nodes, GlobalA, 'Global Stiffness Matrix:')
    ! stop
    return
  end subroutine assemble1D
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt create_simple_array_c det2 eye fun1d_interf fun2d_interf gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getJacobian getXY getXY initialize_global_mats integrate integrate1D integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_2D_row pascal_row pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs write_out_solution
Call graph
assemble1d calls assembleelementalmatrix1d
assembleelementalmatrix1d calls integrate_basis_1d_ie
integrate_basis_1d_ie calls integrate, getalpha
integrate calls integrate2d, integrate1d
integrate2d calls gaussquad
integrate1d calls gaussquad
gaussquad calls gaussquad, gaussquad_rosetta