gaussquad_rosetta – learn_dg
gaussquad_rosetta Subroutine
33 statements
Source File
subroutine gaussquad_rosetta(n, r1, r2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(out) :: r1(n)
real(kind=wp), intent(out) :: r2(n)
Called By
Source Code
gaussquad_rosetta
Source Code
  subroutine gaussquad_rosetta(n, r1, r2)
    ! This code was originally found at the following website:
    !  http://rosettacode.org/wiki/Numerical_integration/Gauss-Legendre_Quadrature#Fortran
    integer,  intent(in)    :: n
    real(wp), intent(out)   :: r1(n), r2(n)
    integer                 :: k
    real(wp), parameter     :: pi = 4._wp*atan(1._wp)
    real(wp)                :: x, f, df, dx
    integer                 :: i,  iter
    real(wp), allocatable   :: p0(:), p1(:), tmp(:)
    p0 = [1._wp]
    p1 = [1._wp, 0._wp]
    do k = 2, n
       tmp = ((2*k-1)*[p1,0._wp]-(k-1)*[0._wp, 0._wp,p0])/k
       p0 = p1; p1 = tmp
    enddo
    outer: do i = 1, n
      x = cos(pi*(i-0.25_wp)/(n+0.5_wp))
      inner: do iter = 1, 10
        f = p1(1); df = 0._wp
        deep: do k = 2, size(p1)
          df = f + x*df
          f  = p1(k) + x * f
        enddo deep
        dx =  f / df
        x = x - dx
        if (abs(dx)<10*epsilon(dx)) exit
      enddo inner
      r1(i) = x
      r2(i) = 2/((1-x**2)*df**2)
    enddo outer
    return
  end subroutine gaussquad_rosetta
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt create_simple_array_c det2 eye fun1d_interf fun2d_interf gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getJacobian getXY getXY initialize_global_mats integrate integrate1D integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_2D_row pascal_row pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs write_out_solution
Call graph
gaussquad calls gaussquad_rosetta, gaussquad
integrate2d calls gaussquad
integrate1d calls gaussquad
integrate calls integrate2d, integrate1d
integrate_basis_1d_ie calls integrate
assembleelementalmatrix2d calls integrate
assembleelementalmatrix1d calls integrate_basis_1d_ie
assemble1d calls assembleelementalmatrix1d