getAlpha – learn_dg
getAlpha Function
22 statements
Source File
public function getAlpha(N) result(alpha)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
Return Value real(kind=wp), dimension(N,N)
Calls
Called By
Source Code
getAlpha
Source Code
  function getAlpha(N) result(alpha)
    integer, intent(in)       :: N
    real(wp), dimension(N,N)  :: alpha
    integer                   :: ii
    real(wp), dimension(N,N)  :: A, B
    A = getA(N)
    B = eye(N)
    call linsolve_quick(N, A, N, B, alpha)
    return
  contains
    pure function getA(N) result(A)
      integer, intent(in)       :: N
      real(wp), dimension(N,N)  :: A
      integer                   :: ii
      real(wp), dimension(N,2)  :: xy
      xy = getxy(N)
      do ii = 1,N
        A(ii,:) = getArow(N, xy(ii,1), xy(ii,2))
      enddo
      return
    end function getA
  end function getAlpha
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_rosetta get_command_argument_wrapper getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs sub1d_interf vandermonde write_out_solution
Call graph
getalpha calls eye, linsolve_quick
linsolve_quick calls linsolve
linsolve calls dgetrs, dgetrf
assembleelementalmatrix calls getalpha