getArow – learn_dg
getArow Function
13 statements
Source File
private pure function getArow(N, xi, eta) result(row)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: N
real(kind=wp), intent(in) :: xi
real(kind=wp), intent(in) :: eta
Return Value real(kind=wp), dimension(N)
Calls
Called By
Source Code
getArow
Source Code
  pure function getArow(N, xi, eta) result(row)
    integer, intent(in)     :: N
    real(wp), intent(in)    :: xi, eta
    real(wp), dimension(N)  :: row
    if ( N == 4 ) then
      ! row = [1._wp, &
      !       xi, eta, &
      !       xi*eta]
      row = pascal(1, xi, eta)
    elseif ( N == 9 ) then
      ! row = [1._wp, &
      !       xi, eta, &
      !       xi**2._wp, xi*eta, eta**2._wp, &
      !       xi**2._wp * eta, xi * eta**2._wp, &
      !       xi**2._wp * eta**2._wp]
      row = pascal(2, xi, eta)
    elseif ( N == 16 ) then
      ! row = [1._wp, &
      !       xi, eta, &
      !       xi**2._wp, xi*eta, eta**2._wp, &
      !       xi**3._wp, xi**2._wp * eta, xi * eta**2._wp, eta**3._wp, &
      !       xi**3._wp * eta, xi**2._wp * eta**2._wp, xi * eta**3._wp, &
      !       xi**3._wp * eta**2._wp, xi**2._wp * eta**3._wp, &
      !       xi**3._wp * eta**3._wp]
      row = pascal(3, xi, eta)
    endif
    return
  end function getArow
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_rosetta getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal pascal_1D_line pascal_2D_quad pascal_2D_row r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs sub1d_interf vandermonde write_out_solution
Call graph
getarow calls pascal
pascal calls pascal_2d_quad, pascal_1d_line
pascal_2d_quad calls pascal_2d_row
getjacobian calls getarow