getIe – learn_dg
getIe Subroutine
12 statements
Source File
subroutine getIe(dii, djj, points, Ie)
Routine to calculate the elemental mass/stiffness matrix based on the derivatives of the basis functions.
Currently only zero-th and first order derivatives are supported. Second order derivatives need to be reduced to first order derivatives in the problem formulation using Green's Theorem
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: dii
Derivative of the first basis function
integer, intent(in) :: djj
Derivative of the second basis function
real(kind=wp), intent(in), dimension(:) :: points
Coordinates of the 1D line element
real(kind=wp), intent(out), dimension(:,:) :: Ie
Output elemental matrix
Calls
Called By
Source Code
getIe
Source Code
  subroutine getIe(dii, djj, points, Ie)
    !*  Routine to calculate the elemental mass/stiffness matrix based on the
    !   derivatives of the basis functions.
    !
    !   Currently only zero-th and first order derivatives are supported. Second
    !   order derivatives need to be reduced to first order derivatives in the
    !   problem formulation using Green's Theorem
    integer,  intent(in)                    :: dii      !! Derivative of the first basis function
    integer,  intent(in)                    :: djj      !! Derivative of the second basis function
    real(wp), intent(in),   dimension(:)    :: points  !! Coordinates of the 1D line element
    real(wp), intent(out),  dimension(:,:)  :: Ie       !! Output elemental matrix
    integer :: ii, jj, order
    order = size(points)-1
    do ii = 1, size(points)
      Ie(ii, :) = [( integrate_basis_1d_Ie(order, ii, jj, dii, djj, points), jj = 1, order+1 )]
    enddo
    return
  end subroutine getIe
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt create_simple_array_c det2 eye fun2d_interf gaussquad gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getIe getJacobian getXY getXY initialize_global_mats integrate integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_2D_row pascal_row pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs sub1d_interf write_out_solution
Call graph
getie calls integrate_basis_1d_ie
integrate_basis_1d_ie calls getalpha, integrate
integrate calls gaussquad
gaussquad calls gaussquad, gaussquad_rosetta
assembleelementalmatrix1d calls getie
assemble1d calls getie