integrate2D – learn_dg
integrate2D Module Function
43 statements
Source File
private function integrate2D(fun, xbnds, ybnds) result(out)
Arguments
Type Intent Optional Attributes Name
procedure(fun2d_interf) :: fun
real(kind=wp), intent(in) :: xbnds(2)
real(kind=wp), intent(in) :: ybnds(2)
Return Value real(kind=wp)
Calls
Called by
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt det2 eye fun1d_interf fun2d_interf gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getJacobian getXY initialize_global_mats integrate integrate1D integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_row pascal_row_2D pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs write_out_solution
Call graph
integrate2d calls gaussquad
gaussquad calls gaussquad, gaussquad_rosetta
integrate calls integrate2d
assembleelementalmatrix2d calls integrate
integrate_basis_1d_ie calls integrate
assembleelementalmatrix1d calls integrate_basis_1d_ie
assemble1d calls assembleelementalmatrix1d