integrate – learn_dg
integrate Subroutine
28 statements
Source File
public subroutine integrate(sub, a, b, result)
Arguments
Type Intent Optional Attributes Name
procedure(sub1d_interf) :: sub
real(kind=wp), intent(in) :: a
real(kind=wp), intent(in) :: b
real(kind=wp), intent(out) :: result
Calls
Called By
Source Code
integrate
Source Code
  subroutine integrate(sub, a, b, result)
    ! This routine uses gauss-legendre quadrature to integrate a 1D line function
    ! Input/Output variables
    real(wp), intent(in)    :: a, b
    real(wp), intent(out)   :: result
    procedure(sub1d_interf) :: sub
    ! Local variables
    integer, parameter    :: N_start = 2
    integer               :: N
    real(wp)              :: result_old, error
    real(wp), parameter   :: eps = epsilon(0e0)
    real(wp), allocatable :: x(:), w(:), y(:)
    N = N_start
    result = 0.0_wp
    error = 1.0_wp
    do
      result_old = result
      allocate(x(N), w(N), y(N))
      call gaussquad(N, x, w)
      call sub(x, y)
      result = sum(y * w)
      deallocate(x, w, y)
      ! error = norm2([result, result_old])
      error = sqrt((result-result_old)**2.0_wp)
      ! error = abs((result-result_old)/(result_old+eps))
      ! print*, N, result, error
      ! print*, N, result, result_old, error, eps
      ! Check if error is acceptable, as well as whether the loop was gone
      ! through at least twice (N = 3, 4, 5...)
      if ( N > N_start .and. &
            norm2( [ error ] ) <= eps ) then
        ! print'(a,i3,a,e13.5)',  'Fun integrated in ', N, &
        !                         ' iterations. Error = ', error
        exit
      else
        N = N + 1
      endif
    enddo
    return
  end subroutine integrate
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt create_simple_array_c det2 eye fun2d_interf gaussquad gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getIe getJacobian getXY getXY initialize_global_mats integrate integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_2D_row pascal_row pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs sub1d_interf write_out_solution
Call graph
integrate calls gaussquad
gaussquad calls gaussquad, gaussquad_rosetta
integrate_basis_1d_ie calls integrate
getie calls integrate_basis_1d_ie
assembleelementalmatrix1d calls getie
assemble1d calls getie