linsolve_quick – learn_dg
linsolve_quick Subroutine
10 statements
Source File
public subroutine linsolve_quick(n, a, nrhs, b, x)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in), dimension(n, n) :: a
integer, intent(in) :: nrhs
real(kind=wp), intent(in), dimension(n, nrhs) :: b
real(kind=wp), intent(out), dimension(n, nrhs) :: x
Calls
Called By
Source Code
linsolve_quick
Source Code
  subroutine linsolve_quick(n, a, nrhs, b, x)
    ! Quick wrapper around linsolve
    integer,  intent(in)                          :: n, nrhs
    real(wp), intent(in),     dimension(n, n)     :: a
    real(wp), intent(in),     dimension(n, nrhs)  :: b
    real(wp), intent(out),    dimension(n, nrhs)  :: x
    integer,                  dimension(n)        :: P
    real(wp),                 dimension(n, n)     :: LU
    call linsolve (n, a, nrhs, b, x, LU, P, .False.)
    return
  end subroutine linsolve_quick
All Procedures
assemble assemble1D assemble1D_c assemble2D_c assembleElementalMatrix assembleElementalMatrix1D_c assembleElementalMatrix2D_c basis_1D cgwt create_simple_array_c det2 eye fun1d_interf fun2d_interf gaussquad gaussquad_rosetta getAlpha1D getAlpha2D getArow getJacobian getXY getXY initialize_global_mats integrate integrate1D integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal_1D_line_c pascal_2D_quad_c pascal_2D_row pascal_row pascal_single_row pascal_single_row_c print_header r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs set_BCs write_out_solution
Call graph
linsolve_quick calls linsolve
linsolve calls dgetrf, dgetrs
driver1d calls linsolve_quick
driver2d calls linsolve_quick
getalpha2d calls linsolve_quick
getalpha1d calls linsolve_quick