linsolve – learn_dg
linsolve Subroutine
35 statements
Source File
public subroutine linsolve(n, a, nrhs, b, x, LU, P, toggle)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in), dimension(n, n) :: a
integer, intent(in) :: nrhs
real(kind=wp), intent(in), dimension(n, nrhs) :: b
real(kind=wp), intent(out), dimension(n, nrhs) :: x
real(kind=wp), intent(inout), dimension(n, n) :: LU
integer, intent(inout), dimension(n) :: P
logical, intent(in) :: toggle
Calls
Called By
Source Code
linsolve
Source Code
  subroutine linsolve (n, a, nrhs, b, x, LU, P, toggle)
    ! This routine is a wrapper dgesv, splitting it into its two primary
    ! components:
    !             dgetrf - Decomposes A into P*L*U
    !             dgetrs - Uses P*L*U to solve for x (Ax=b => (P*L*U)x=b)
    !
    ! Splitting these two up like this allows you to save the decomposed
    ! version of 'a' so that you don't have to do it again. If 'toggle' is
    ! equal to true, then the decomposition has already occured and LU can be
    ! trusted - OK to skip dgetrf
    ! Dummy variables
    integer,  intent(in)                          :: n, nrhs
    integer,  intent(inout),  dimension(n)        :: P
    real(wp), intent(in),     dimension(n, nrhs)  :: b
    real(wp), intent(in),     dimension(n, n)     :: a
    real(wp), intent(out),    dimension(n, nrhs)  :: x
    real(wp), intent(inout),  dimension(n, n)     :: LU
    logical,  intent(in)                          :: toggle
    ! Local variables
    integer                                       :: info
    integer,                  dimension(n)        :: my_P
    real(wp),                 dimension(n, n)     :: my_a
    real(wp),                 dimension(n, nrhs)  :: my_b
    my_a = a
    my_b = b
    if ( .not. toggle ) then
      call dgetrf (n, n, my_a, n, my_P, info)
      if ( info /= 0 ) then
        write ( *, '(a)' ) ' '
        write ( *, '(a)' ) 'DGETRF'
        write ( *, '(a,i8)' ) '  Factorization failed, INFO = ', info
        stop
      endif
      LU  = my_a
      P   = my_P
    endif
    call dgetrs ('No transpose', n, nrhs, LU, n, P, my_b, n, info)
    if ( info /= 0 ) then
      write ( *, '(a)' ) ' '
      write ( *, '(a)' ) 'DGETRS'
      write ( *, '(a,i8)' ) '  Back substitution failed, INFO = ', info
      stop
    endif
    x = my_b
    return
  end subroutine linsolve
All Procedures
assemble assembleElementalMatrix basis_1D cgwt det2 eye fun2d_interf gaussquad gaussquad_rosetta getAlpha getArow getIe getJacobian getxy initialize_global_mats integrate integrate2D integrate_basis_1d_Ie inv2 lgwt linsolve linsolve_quick pascal pascal_1D_line pascal_2D_quad pascal_2D_row r8mat_print r8mat_print_some read_gmsh_file_1D set_BCs sub1d_interf vandermonde write_out_solution
Call graph
linsolve calls dgetrf, dgetrs
linsolve_quick calls linsolve
main calls linsolve_quick
vandermonde calls linsolve_quick
getalpha calls linsolve_quick
doubleint calls linsolve_quick
integrate_basis_1d_ie calls vandermonde
getie calls integrate_basis_1d_ie
assembleelementalmatrix calls getalpha