driver1D – learn_dg
driver1D Program
22 statements
Source File
Uses
iso_fortran_env
mod_linalg
mod_misc
mod_io
mod_assembly
Calls
Variables
diff vel num_nodes nodes2vertex cells points GlobalB GlobalX GlobalA dg
Source Code
driver1D
Variables
Type Attributes Name Initial
real(kind=wp), parameter :: diff = 0.1_wp
real(kind=wp), parameter :: vel = -5._wp
integer :: num_nodes
integer, dimension(:), allocatable :: nodes2vertex
integer, dimension(:,:), allocatable :: cells
real(kind=wp), dimension(:), allocatable :: points
real(kind=wp), dimension(:), allocatable :: GlobalB
real(kind=wp), dimension(:), allocatable :: GlobalX
real(kind=wp), dimension(:,:), allocatable :: GlobalA
logical :: dg
Source Code
program driver1D
    use, intrinsic :: iso_fortran_env, only: wp=>real64
    use :: mod_linalg,    only: linsolve_quick
    use :: mod_misc,      only: r8mat_print
    use :: mod_io,        only: read_gmsh_file_1D, write_out_solution
    use :: mod_assembly,  only: initialize_global_mats, assemble, set_BCs
    implicit none
    real(wp), parameter                   :: diff = 0.1_wp, vel = -5._wp
    integer                               :: num_nodes
    integer,  dimension(:),   allocatable :: nodes2vertex
    integer,  dimension(:,:), allocatable :: cells
    real(wp), dimension(:),   allocatable :: points, GlobalB, GlobalX
    real(wp), dimension(:,:), allocatable :: GlobalA
    logical                               :: dg
    ! dg = .true.
    dg = .false.
    call read_gmsh_file_1D(num_nodes, nodes2vertex, cells, points, dg)
    ! stop
    call initialize_global_mats(num_nodes, GlobalA, GlobalB, GlobalX)
    call assemble(points, cells, diff, vel, GlobalA)
    call set_BCs(points, GlobalB, GlobalA)
    ! call r8mat_print(num_nodes, num_nodes, GlobalA, 'Global Stiffness matrix:')
    ! stop
    call linsolve_quick(num_nodes, GlobalA, 1, GlobalB, GlobalX)
    ! call r8mat_print(num_nodes, 1, GlobalB, 'Global RHS:')
    ! call r8mat_print(num_nodes, 1, GlobalX, 'Global Solution Vector:')
    call write_out_solution(num_nodes, points, GlobalX)
end program driver1D
All Programs
driver1D driver2D
Call graph
driver1d calls write_out_solution, linsolve_quick, assemble, read_gmsh_file_1d, initialize_global_mats, set_bcs
linsolve_quick calls linsolve
read_gmsh_file_1d calls print_header
linsolve calls dgetrf, dgetrs