driver1 – learn_dg
driver1 Program
22 statements
Source File
Uses:
iso_fortran_env
linalg
misc
io
assembly
Calls
Variables
diff vel num_nodes order nodes2vertex elem_conn xcoords GlobalB GlobalX GlobalA dg
Source Code
driver1
Variables
Type Attributes Name Initial
real(kind=wp), parameter :: diff = 0.1_wp
real(kind=wp), parameter :: vel = -5._wp
integer :: num_nodes
integer, dimension(:), allocatable :: order
integer, dimension(:), allocatable :: nodes2vertex
integer, dimension(:,:), allocatable :: elem_conn
real(kind=wp), dimension(:), allocatable :: xcoords
real(kind=wp), dimension(:), allocatable :: GlobalB
real(kind=wp), dimension(:), allocatable :: GlobalX
real(kind=wp), dimension(:,:), allocatable :: GlobalA
logical :: dg
Source Code
program driver1
  use, intrinsic :: iso_fortran_env, only: wp=>real64
  use :: linalg, only: linsolve_quick
  use :: misc, only: r8mat_print
  use :: io, only: read_gmsh_file_1D, write_out_solution
  use :: assembly, only: initialize_global_mats, assemble, set_BCs
  implicit none
  real(wp), parameter                   :: diff = 0.1_wp, vel = -5._wp
  integer                               :: num_nodes
  integer,  dimension(:),   allocatable :: order, nodes2vertex
  integer,  dimension(:,:), allocatable :: elem_conn
  real(wp), dimension(:),   allocatable :: xcoords, GlobalB, GlobalX
  real(wp), dimension(:,:), allocatable :: GlobalA
  logical                               :: dg
  ! dg = .true.
  dg = .false.
  call read_gmsh_file_1D(num_nodes, order, nodes2vertex, elem_conn, xcoords, dg)
  ! stop
  call initialize_global_mats(num_nodes, GlobalA, GlobalB, GlobalX)
  call assemble(order, xcoords, elem_conn, GlobalA, diff, vel)
  call set_BCs(xcoords, GlobalB, GlobalA)
  ! call r8mat_print(num_nodes, num_nodes, GlobalA, 'Global Stiffness matrix:')
  ! stop
  call linsolve_quick(num_nodes, GlobalA, 1, GlobalB, GlobalX)
  ! call r8mat_print(num_nodes, 1, GlobalB, 'Global RHS:')
  ! call r8mat_print(num_nodes, 1, GlobalX, 'Global Solution Vector:')
  call write_out_solution(num_nodes, xcoords, GlobalX)
end program driver1
All Programs
driver1 driver2
Call graph
driver1 calls read_gmsh_file_1d, assemble, set_bcs, initialize_global_mats, write_out_solution, linsolve_quick
assemble calls getie
linsolve_quick calls linsolve
linsolve calls dgetrs, dgetrf